# Header
menu:
  # 悄悄话: http://bluesh.me
rss: /atom.xml
# title: GARY.SHEN

author: ALEVEN.SH
aboutme: So what~

# Content
excerpt_link: 阅读全文
fancybox: false
date_format: 'YYYY年MM月DD日'

socials:
  github: "https://github.com/bluesh"
  email: "coffee.xuy@gmail.com"
  twitter: "https://twitter.com/Bluesh0"


# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

#主题方案
highlight_theme: atom light

# widget behavior
archive_type: 'monthly'
show_count: false

disqus_shortname: coffeexu

# Miscellaneous
google_analytics: 'UA-97572000-1'
gauges_analytics:
favicon: /blog/images/avatar.jpg
avatar: "/blog/images/avatar.jpg"
twitter:
google_plus:
fb_admins:
fb_app_id:
